//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookletDetail
    {
        public int IndexID { get; set; }
        public string Date { get; set; }
        public string CenterCode { get; set; }
        public string CenterName { get; set; }
        public string SubjectCode { get; set; }
        public string Count { get; set; }
    }
}
