//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseSubject()
        {
            this.StudentRepeaterDetails = new HashSet<StudentRepeaterDetail>();
        }
    
        public int CourseSubjectId { get; set; }
        public int CourseId { get; set; }
        public int SubjectId { get; set; }
        public int Semester { get; set; }
        public bool HasExamination { get; set; }
        public int TotalTeachingHours { get; set; }
        public bool DegreeConsider { get; set; }
        public bool IsMandatory { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentRepeaterDetail> StudentRepeaterDetails { get; set; }
    }
}
