//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class DegreeMax
    {
        public int DegreeID { get; set; }
        public string DegreeName { get; set; }
        public Nullable<double> YearSem { get; set; }
        public Nullable<double> SemesterMax { get; set; }
    }
}
