//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationBatchItem
    {
        public int EvaluationBatchItemId { get; set; }
        public int BatchId { get; set; }
        public string OrgDummyNumber { get; set; }
        public string IndexedDummyNumber { get; set; }
        public string IndexedRegNo { get; set; }
        public string VerifiedRegNo { get; set; }
        public string TempRegNo { get; set; }
        public string ReviewedRegNo { get; set; }
        public Nullable<int> IndexedUserId { get; set; }
        public Nullable<int> VerifiedUserId { get; set; }
        public Nullable<int> ReviewedUserId { get; set; }
        public Nullable<System.DateTime> IndexedDate { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string UnitName { get; set; }
        public Nullable<bool> IsMigrated { get; set; }
        public Nullable<int> OldBatchItemId { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public Nullable<int> LockedUserId { get; set; }
        public string ErrorText { get; set; }
        public bool HasError { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual EvaluationBatch EvaluationBatch { get; set; }
    }
}
