//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvaluationBatch()
        {
            this.EvaluationBatchItems = new HashSet<EvaluationBatchItem>();
        }
    
        public int BatchId { get; set; }
        public int OldBatchId { get; set; }
        public string BaseFolder { get; set; }
        public int BatchNo { get; set; }
        public string CourseName { get; set; }
        public int Semester { get; set; }
        public string PaperName { get; set; }
        public string PaperCode { get; set; }
        public int PartNo { get; set; }
        public string RequestOwner { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> PrintedDate { get; set; }
        public bool IsDeleted { get; set; }
        public int ImportBatchId { get; set; }
        public System.DateTime ImportedDate { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsIndexed { get; set; }
        public Nullable<bool> IsReviewed { get; set; }
        public string PGCourseName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluationBatchItem> EvaluationBatchItems { get; set; }
    }
}
