//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupName
    {
        public int GroupID { get; set; }
        public string GroupName1 { get; set; }
        public string SubjectName { get; set; }
        public Nullable<double> MarksCardOrder { get; set; }
    }
}
