//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INFINITY_MUEntities : DbContext
    {
        public INFINITY_MUEntities()
            : base("name=INFINITY_MUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<College> Colleges { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<CourseSubject> CourseSubjects { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<SubjectMark> SubjectMarks { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<StudentRepeaterDetail> StudentRepeaterDetails { get; set; }
        public virtual DbSet<StudentBill> StudentBills { get; set; }
        public virtual DbSet<SubjectComponent> SubjectComponents { get; set; }
    }
}
