//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdbSubjectPaperDetail
    {
        public int SubjectId { get; set; }
        public string StreamName { get; set; }
        public string StreamCode { get; set; }
        public string StreamType { get; set; }
        public string StreamSubjectName { get; set; }
        public string StreamSubjectCode { get; set; }
        public string SubjectPaperName { get; set; }
        public string SubjectPaperCode { get; set; }
        public string SubjectPaperType { get; set; }
        public byte YearSem { get; set; }
        public Nullable<double> TheoryMax { get; set; }
        public Nullable<double> TheoryMin { get; set; }
        public Nullable<double> TheoryIAMax { get; set; }
        public Nullable<double> TheoryIAMin { get; set; }
        public Nullable<double> PracticalExamMax { get; set; }
        public Nullable<double> PracticalClassRecordMax { get; set; }
        public Nullable<double> PracticalMax { get; set; }
        public Nullable<double> PracticalMin { get; set; }
        public Nullable<double> PracticalIAMax { get; set; }
        public Nullable<double> PracticalIAMin { get; set; }
        public Nullable<double> TheoryAndTheoryIAMin { get; set; }
        public Nullable<double> PracticalAndPracticalIAMin { get; set; }
        public Nullable<double> VivaVoiceMin { get; set; }
        public Nullable<double> VivaVoice { get; set; }
        public Nullable<double> TotalPassMarks { get; set; }
        public Nullable<double> PracticalPracticalIAAndVivaVoiceMin { get; set; }
        public Nullable<double> PracticalAndVivaMin { get; set; }
    }
}
