//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldResultMap
    {
        public int OldResultId { get; set; }
        public string RegisterNumber { get; set; }
        public int YearSem { get; set; }
        public int SemsterMax { get; set; }
        public int SemesterMarks { get; set; }
        public decimal SemesterGPA { get; set; }
        public int SemesterCredits { get; set; }
        public Nullable<decimal> SemesterWeightage { get; set; }
        public string Remarks { get; set; }
        public int LastExaminationBatchId { get; set; }
        public string CourseCode { get; set; }
    }
}
