//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldSemesterMark
    {
        public int OldResultId { get; set; }
        public int LastExaminationId { get; set; }
        public string RegNo { get; set; }
        public int Semester { get; set; }
        public int SemesterMarks { get; set; }
        public int SemesterPercentage { get; set; }
        public bool IsSemesterPass { get; set; }
    }
}
