//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revaluation
    {
        public int ResultID { get; set; }
        public string CourseName { get; set; }
        public string Semester { get; set; }
        public string RegisterNumber { get; set; }
        public string StudentName { get; set; }
        public string SubjectCode { get; set; }
        public string SubjectName { get; set; }
        public string DummyNo { get; set; }
        public string BatchNo { get; set; }
        public Nullable<bool> IsPersonalSeeing { get; set; }
        public Nullable<bool> IsRevaluation { get; set; }
    }
}
