//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentBill
    {
        public int BillId { get; set; }
        public int ExaminationId { get; set; }
        public int StudentId { get; set; }
        public bool EligibleForConcession { get; set; }
        public string BillSegment { get; set; }
        public bool IsEdited { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsCreatedManually { get; set; }
        public string HallticketUniqueNumber { get; set; }
        public Nullable<int> BatchId { get; set; }
        public double Total { get; set; }
        public int ApprovalStatus { get; set; }
        public int RegistrationStatus { get; set; }
        public int CreatedUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedUserId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
