//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentRepeaterDetails = new HashSet<StudentRepeaterDetail>();
        }
    
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string RegisterNumber { get; set; }
        public string DateOfBirth { get; set; }
        public Nullable<int> YearOfAdmission { get; set; }
        public Nullable<int> PassedOutYear { get; set; }
        public int Gender { get; set; }
        public Nullable<int> YearSem { get; set; }
        public string Nationality { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string PermanantAddress { get; set; }
        public string LocalAddress { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public string GaurdiansName { get; set; }
        public int CasteCategoryId { get; set; }
        public int CollegeId { get; set; }
        public int DegreeId { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> SpecializationId { get; set; }
        public Nullable<int> Photo { get; set; }
        public int CreatedUserId { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<int> DeletedUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual College College { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual Degree Degree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentRepeaterDetail> StudentRepeaterDetails { get; set; }
    }
}
