//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectMark
    {
        public int SubjectMarkId { get; set; }
        public int Min { get; set; }
        public int Max { get; set; }
        public int SubjectComponentId { get; set; }
        public int SubjectId { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
