//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUOffLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class UGFinalResultTable
    {
        public int FinalResultId { get; set; }
        public string RegisterNumber { get; set; }
        public string StudentName { get; set; }
        public string CollegeName { get; set; }
        public string CollegeCode { get; set; }
        public string DegreeName { get; set; }
        public int YearSem { get; set; }
        public string GroupName { get; set; }
        public string SubGroupName { get; set; }
        public string SubjectName { get; set; }
        public string SubjectCode { get; set; }
        public string TheoryGrace { get; set; }
        public string TheoryMarks { get; set; }
        public string TheoryMin { get; set; }
        public string TheoryMax { get; set; }
        public string TheoryTotal { get; set; }
        public string TheoryIAMarks { get; set; }
        public string TheoryIAGrace { get; set; }
        public string TheoryIAMin { get; set; }
        public string TheoryIAMax { get; set; }
        public string TheoryIATotal { get; set; }
        public string TheoryNetTotal { get; set; }
        public string PracticalMarks { get; set; }
        public string PracticalGrace { get; set; }
        public string PracticalMin { get; set; }
        public string PracticalMax { get; set; }
        public string PracticalTotal { get; set; }
        public string PracticalIAMarks { get; set; }
        public string PracticalIAGrace { get; set; }
        public string PracticalIAMin { get; set; }
        public string PracticalIAMax { get; set; }
        public string PracticalIATotal { get; set; }
        public string PracticalNetTotal { get; set; }
        public string VivaVoice { get; set; }
        public string VivaVoiceMin { get; set; }
        public string VivaVoiceMax { get; set; }
        public string SubjectTotal { get; set; }
        public string SubGroupTotal { get; set; }
        public string GroupTotal { get; set; }
        public string TotalMarks { get; set; }
        public int SubjectMin { get; set; }
        public int SubjectMax { get; set; }
        public Nullable<double> SubjectCredits { get; set; }
        public Nullable<double> SubjectGPA { get; set; }
        public Nullable<double> SubjectGPW { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsSubjectPass { get; set; }
        public Nullable<double> MarksPercent { get; set; }
        public string AlphaSign { get; set; }
        public Nullable<int> SemesterCredits { get; set; }
        public Nullable<int> SemesterMax { get; set; }
        public Nullable<int> SemesterMin { get; set; }
        public Nullable<int> SemesterTotal { get; set; }
        public Nullable<double> SemesterPercentage { get; set; }
        public Nullable<double> SemesterGPA { get; set; }
        public string SemesterClass { get; set; }
        public string SemesterAlphaSign { get; set; }
        public Nullable<bool> IsSemesterPass { get; set; }
        public string Remarks { get; set; }
        public string YearText { get; set; }
    }
}
